# docker-compose.yaml

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A drf_online_school worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
