# docker-compose.yaml

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A drf_online_school worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
